version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.11
    steps:
      - checkout
      - run:
          name: Install tox
          command: pip install tox
      - run:
          name: Run tox tests
          command: tox -e py311

workflows:
  version: 2
  test:
    jobs:
      - test
